# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- id: bgproxy
  env:
  - CGO_ENABLED=0
  main: ./cmd/bgproxy/
  binary: bgproxy
  flags:
    - -trimpath
  ldflags:
    - -X github.com/theoremoon/bgproxy/common.Version={{.Version}}
- id: bgproxyctl
  env:
  - CGO_ENABLED=0
  main: ./cmd/bgproxyctl/
  binary: bgproxyctl
  flags:
    - -trimpath
  ldflags:
    - -X github.com/theoremoon/bgproxy/common.Version={{.Version}}

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
